### ISSUE TITLE
reproj broken for proj4 and PROJ > 5

### ISSUE THREAD

**Issue by rsbivand** [hypertidy/reproj#7]
Because proj4 is not properly maintained, proj4 will not install where proj_api.h is absent. This can be fixed (add "-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H" to PKG_CPPFLAGS) for PROJ 6, but PROJ 7 due in 10 months will remove this option. Please ask Simon to address this. I noticed this when running reverse dependency checks.

**Comment by mdsumner** [comment]
Ok thanks, I asked this with the proj4 package project site. 

Anyone else reading this: proj4 hasn't been updated on cran since 2012, though several fixes have been applied.
